# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
# 煞笔微软式中文传到 GitHub 文档上了，还用英文看吧，否则排版就是一团乱麻
version: 2

updates:
  # update npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3